[package]
name = "aws-spotter"
version = "3.2.1"
edition = "2021"

[dependencies]
rusoto_core = "0.48.0"
rusoto_ec2 = "0.48.0"
clap = { version = "4.0", features = ["derive"] }
chrono = "0.4"
tokio = { version = "1", features = ["full"] }
colored = "2.0"